import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/footer/Footer'
import Provider from '@/SessionProvider'
import { Toaster } from 'react-hot-toast'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Expressive Mind',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
        <Navbar />
        <Toaster />
        <main className='z-0 min-h-screen'>
        {children}
        </main>
        <Footer />
        </Provider>
        </body>
    </html>
  )
}
